apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ include "cronjob.fullname" . }}
  labels: {{- include "cronjob.labels" . | nindent 4 }}
spec:
  suspend: {{ .Values.suspend }}
  schedule: {{ .Values.schedule | quote }}
  concurrencyPolicy: {{ .Values.concurrencyPolicy }}
{{- if .Values.startingDeadlineSeconds }}
  startingDeadlineSeconds: {{ .Values.startingDeadlineSeconds }}
{{- end }}
  successfulJobsHistoryLimit: {{ .Values.successfulJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ .Values.failedJobsHistoryLimit }}
  jobTemplate:
    spec:
      template:
        metadata:
          name: {{ include "cronjob.fullname" . }}
          labels: {{- include "cronjob.labels" . | nindent 12 }}
        spec:
          restartPolicy: Never
          terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
        {{- with .Values.imagePullSecrets }}
          imagePullSecrets:
          {{- range . }}
            - name: {{ . }}
          {{- end }}
        {{- end }}
          containers:
            - name: job
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
            {{- with .Values.command }}
              command:
              {{- range . }}
                - {{ . | quote }}
              {{- end }}
            {{- end }}
              envFrom:
                - secretRef:
                    name: {{ include "cronjob.fullname" . }}-envs
            {{- with .Values.resources }}
              resources:
                {{ toYaml . | indent 16 | trim }}
            {{- end }}
        {{- with .Values.nodeSelector }}
          nodeSelector:
            {{ toYaml . | indent 12 | trim }}
        {{- end }}
        {{- with .Values.affinity }}
          affinity:
            {{ toYaml . | indent 12 | trim }}
        {{- end }}
        {{- with .Values.tolerations }}
          tolerations:
            {{ toYaml . | indent 12 | trim }}
        {{- end }}
