image:
  repository: alpine
  tag: 3.8
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: "cronjob"

suspend: false

resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}
tolerations: []
affinity: {}

schedule: "* * * * *"
concurrencyPolicy: Forbid
startingDeadlineSeconds: ""
successfulJobsHistoryLimit: 1
failedJobsHistoryLimit: 3
terminationGracePeriodSeconds: 30

env: {}
  # PLATFORM: kubernetes

# Override docker image entrypoint
command:
  - echo
  - hello
