{{- if .Values.postUpgradeJob.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "app.fullname" . }}-post-upgrade-job-env
  labels:
    {{- include "app.labels" . | nindent 4 }}
stringData:
{{ toYaml .Values.postUpgradeJob.env | indent 2 }}
{{- end }}