name: Build Helm charts and publish to Github Pages

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  publish:
    runs-on: ubuntu-latest
    container: ubuntu
    steps:
      - uses: actions/checkout@v2
      - uses: azure/setup-helm@v3
      - name: Package charts
        run: |
          for dir in charts/*/; do
              echo "Packaging chart: $dir"
              helm package $dir -d dist/
          done
      - name: Create chart index
        run: |
          helm repo index --url https://medhy-brasil.github.io/charts dist
      - name: Setup Pages
        uses: actions/configure-pages@v2
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: 'dist'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
