name: Build Helm and Sync to DO Spaces

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: self-hosted
    container: ubuntu
    steps:
      - uses: actions/checkout@v2
      - name: Package charts
        run: |
          for dir in charts/*/; do
              echo "Packaging chart: $dir"
              helm package $dir -d dist/
          done
      - name: Create chart index
        run: |
          helm repo index --url https://medhy-brasil.github.io/charts --merge index.yaml .


